import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/NavBar";
import Footer from "./components/Footer";
import "bootstrap/dist/css/bootstrap.css";
import { Marcellus } from "next/font/google";
import Script from "next/script";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const pd = Marcellus({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pd.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
      <Script
        defer
        data-domain="coffeecommerce.nickmelms.dev"
        src="https://plausible.io/js/script.js"
      />
    </html>
  );
}
